name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      npm_config_cache: /tmp/.npm-cache
    container:
      image: mcr.microsoft.com/playwright:v1.53.0-jammy
      options: --user 1001
    steps:
      - uses: actions/checkout@v4 

      - name: Install dependencies
        run: npm ci

      - name: Run Smoke Tests
        run: npx playwright test --grep @smoke --reporter=html --output=playwright-report-smoke

      - name: Upload Smoke Test Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-smoke
          path: playwright-report-smoke/
          retention-days: 30

  regression:
    runs-on: ubuntu-latest
    needs: smoke
    env:
      npm_config_cache: /tmp/.npm-cache
    container:
      image: mcr.microsoft.com/playwright:v1.53.0-jammy
      options: --user 1001
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Regression Tests
        run: npx playwright test --grep @regression --reporter=html --output=playwright-report-regression

      - name: Upload Regression Test Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-regression
          path: playwright-report-regression/
          retention-days: 30