name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      npm_config_cache: /tmp/.npm-cache
      PW_REPORT_FOLDER: playwright-report-smoke
    container:
      image: mcr.microsoft.com/playwright:v1.53.0-jammy
      options: --user 1001
    steps:
      - uses: actions/checkout@v4 

      - name: Install dependencies
        run: npm ci

      - name: Run Smoke Tests
        run: npm run test:smoke || true

      - name: Upload Smoke Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-smoke
          path: playwright-report-smoke/
          retention-days: 30

      - name: Send Slack notification
        run: |
          REPORT_FILE="$PW_REPORT_FOLDER/report.json"
          if grep -q '"status": "failed"' "$REPORT_FILE"; then
            STATUS="❌ Playwright - Smoke tests failed. Please check the report."
          else
            STATUS="✅ Playwright - Smoke tests passed"
          fi

          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$STATUS on *${{ github.repository }}* (\`${{ github.ref_name }}\`) by \`${{ github.actor }}\`.\"}" \
            ${{ secrets.SLACK_WEBHOOK_URL }}

  regression:
    runs-on: ubuntu-latest
    needs: smoke
    env:
      npm_config_cache: /tmp/.npm-cache
      PW_REPORT_FOLDER: playwright-report-regression
    container:
      image: mcr.microsoft.com/playwright:v1.53.0-jammy
      options: --user 1001
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Regression Tests
        run: npm run test:regression || true

      - name: Upload Regression Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-regression
          path: playwright-report-regression/
          retention-days: 30

      - name: Send Slack notification
        run: |
          REPORT_FILE="$PW_REPORT_FOLDER/report.json"
          if grep -q '"status": "failed"' "$REPORT_FILE"; then
            STATUS="❌ Playwright - Regression tests failed. Please check the report."
          else
            STATUS="✅ Playwright - Regression tests passed"
          fi

          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$STATUS on *${{ github.repository }}* (\`${{ github.ref_name }}\`) by \`${{ github.actor }}\`.\"}" \
            ${{ secrets.SLACK_WEBHOOK_URL }}
  
  deploy-report:
    runs-on: ubuntu-latest
    needs: regression
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Smoke Report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report-smoke
          path: report/smoke

      - name: Download Regression Report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report-regression
          path: report/regression

      - name: Deploy Both Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report

      - name: Send Slack Notification with Both Links
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"*Playwright Test Reports Available:*\\n🔹 Smoke Report: https://sakthijas.github.io/playwright-samp1/smoke/\\n🔹 Regression Report: https://sakthijas.github.io/playwright-samp1/regression/\"
          }" ${{ secrets.SLACK_WEBHOOK_URL }}