name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      npm_config_cache: /tmp/.npm-cache
      PW_REPORT_FOLDER: playwright-report-smoke
    container:
      image: mcr.microsoft.com/playwright:v1.53.0-jammy
      options: --user 1001
    steps:
      - uses: actions/checkout@v4 

      - name: Install dependencies
        run: npm ci

      - name: Run Smoke Tests
        run: npx playwright test --grep @smoke

      - name: Upload Smoke Test Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-smoke
          path: playwright-report-smoke/
          retention-days: 30

  regression:
    runs-on: ubuntu-latest
    needs: smoke
    env:
      npm_config_cache: /tmp/.npm-cache
      PW_REPORT_FOLDER: playwright-report-regression
    container:
      image: mcr.microsoft.com/playwright:v1.53.0-jammy
      options: --user 1001
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Regression Tests
        run: npx playwright test --grep @regression

      - name: Upload Regression Test Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-regression
          path: playwright-report-regression/
          retention-days: 30

      - name: Send Slack notification on success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ Playwright tests passed on *${{ github.repository }}* (`${{ github.ref_name }}`) by `${{ github.actor }}`."}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send Slack notification on failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"❌ Playwright tests failed on *${{ github.repository }}* (`${{ github.ref_name }}`) by `${{ github.actor }}`. Please check the logs."}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}